### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dissension** [HAHAYOUDEAD/Architect#1]
[20:39:07.058] ModData Initialized - 1.5.4
[20:39:07.060] [Architect] System.IO.FileNotFoundException: Could not load file or assembly 'LocalizationUtilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'LocalizationUtilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Architect.ArcMain.OnInitializeMelon()
   at MelonLoader.MelonBase.LoaderInitialized() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 446
[20:39:07.077] [ModComponent] Release Compilation
[20:39:07.099] [ModComponent] Reading zip file: 'Architect.modcomponent'
[20:39:07.116] [ModComponent] Error Loading .modcomponent file
'System.IO.FileNotFoundException: Could not load file or assembly 'LocalizationUtilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'LocalizationUtilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ModComponent.Mapper.ZipFileLoader.TryHandleJson(String zipFilePath, String internalPath, String text)
   at ModComponent.Mapper.ZipFileLoader.TryHandleFile(String zipFilePath, String internalPath, FileType fileType, MemoryStream unzippedFileStream) in C:\REPOS\ModComponent\ModComponent\Mapper\ZipFileLoader.cs:line 180
   at ModComponent.Mapper.ZipFileLoader.LoadZipFile(String MCFilePath, FileStream fileStream) in C:\REPOS\ModComponent\ModComponent\Mapper\ZipFileLoader.cs:line 115
   at ModComponent.Mapper.ZipFileLoader.LoadMCFile(String MCFilePath) in C:\REPOS\ModComponent\ModComponent\Mapper\ZipFileLoader.cs:line 75
   at ModComponent.Mapper.ZipFileLoader.LoadMCFilesInDirectory(String directory, Boolean recursive) in C:\REPOS\ModComponent\ModComponent\Mapper\ZipFileLoader.cs:line 42'
   
   Ingame holding "B" does nothing

**Comment by HAHAYOUDEAD** [comment]
can you atleast attempt to read the log you sent? install LocalizationUtilities, it's a dependency of ModComponent

**Comment by Dissension** [comment]
well, my bad 😅
sorry
